#ddev-generated
# trunk-ignore-all(trivy/DS002)
# trunk-ignore-all(trivy/DS026)
# trunk-ignore-all(checkov/CKV_DOCKER_2)
# trunk-ignore-all(checkov/CKV_DOCKER_3)

# https://github.com/raineorshine/npm-check-updates
RUN npm install -g npm-check-updates
